/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/git-svg-transformed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Git = (props) => {
  const { nodes } = useGLTF('../models/git-svg-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} position={[-37.233, 50.062, 33.39]} rotation={[0, Math.PI / 4, -Math.PI]} scale={[-1.087, 1.087, 1.087]} />
    </group>
  )
}

useGLTF.preload('../models/git-svg-transformed.glb')

export default Git
