/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/skillsLogos/reactLogo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const ReactLogo = (props) => {
  const { nodes, materials } = useGLTF('../skillsLogos/reactLogo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 7.935, 18.102]} rotation={[0, 0, -Math.PI / 2]} scale={[39.166, 39.166, 52.734]}>
          <mesh geometry={nodes['React-Logo_Material002_0'].geometry} material={materials['Material.002']} position={[-1.039, 0, 2.449]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.089, -1.132, -1.089]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../skillsLogos/reactLogo.glb')

export default ReactLogo