/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Untitled.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const GitHub = (props) => {
  const { nodes, materials } = useGLTF('../models/Untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.005, 0]}>
        <group rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={-4.167}>
          <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[-12, -11.702, -2.5]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../models/Untitled.glb')

export default GitHub
